owner: suritptyltd
repo: mhgupptime
sites:
  - name: office.com
    url: https://office.com
  - name: momentohospitality.com.au
    url: https://momentohospitality.com.au
  - name: bellavistahotel.com.au
    url: https://bellavistahotel.com.au
  - name: mullanes.com.au
    url: https://mullanes.com.au
  - name: hillsidehotel.com.au
    url: https://hillsidehotel.com.au
  - name: thedukeofdural.com.au
    url: https://thedukeofdural.com.au
  - name: thegovernorhotel.com.au
    url: https://thegovernorhotel.com.au
  - name: learnhospo.com.au
    url: https://learnhospo.com.au
  - name: bangbangdrinks.com
    url: https://www.bangbangdrinks.com
  - name: thedrinkstore.com.au
    url: https://www.thedrinkstore.com.au
  - name: origincoffeeliqueur.com
    url: https://origincoffeeliqueur.com
  - name: HQ Internet
    url: $MHQ_GW
  - name: Bella Internet
    check: "tcp-ping"
    url: $BVH_GW
    port: 8443
  - name: Mullane's Internet
    url: $MLH_GW
  - name: Duke Internet
    check: "tcp-ping"
    url: $TDH_GW
    port: 8443
  - name: Hillside Internet
    url: $HSH_GW
  - name: Governor Internet
    url: $TGH_GW
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.momento.group
  # baseUrl: /mhgupptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
